# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b301c6bbc9549974071ff2164e042d8dfb22ae7ecfd20adda14ae97e6656a42bc048706855f3bf028d2175ebe5005e74e651760876df0c29e30932f061d5a54

test:
  secret_key_base: 3a30d9288ece21df43597be783e7bb1696712684d446ef3d692eb691025f9f5cc2c2b7865bf34f6a698dbc89c9a9fd170a71eac1ff4a13a34dbc21ee4e1a79b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
